### ISSUE TITLE
Converting BTC values to GBP and EUR

### ISSUE THREAD

**Issue by nberrisford** [PyDataBlog/Coinsta#3]
Hi Bernard

I'm currently using the following code which derives the current value of BTC against US Dollars:

**# import the Current class
from coinsta.core import Current**

**# get current market information on a specified crypto
btc_current = Current.get_current('btc')  # a pandas dataframe object**

**#print(btc_current)
btc_current_price = btc_current.loc['price'] [0]
print(btc_current_price)**

However, as I live in the UK, it would be really useful to be able to derive the current value of BTC against GBP (British Pounds), and maybe even EUR (Euros)!

Best regards,
Niall

**Comment by PyDataBlog** [comment]
> Hi Bernard
> 
> I'm currently using the following code which derives the current value of BTC against US Dollars:
> 
> **# import the Current class from coinsta.core import Current**
> 
> **# get current market information on a specified crypto btc_current = Current.get_current('btc') # a pandas dataframe object**
> 
> **#print(btc_current) btc_current_price = btc_current.loc['price'] [0] print(btc_current_price)**
> 
> However, as I live in the UK, it would be really useful to be able to derive the current value of BTC against GBP (British Pounds), and maybe even EUR (Euros)!
> 
> Best regards,
> Niall

Hi Niall, 

The next version of Coinsta will be updated to accommodate currency conversions as well as support the new PRO CoinMarketAPI as CoinMarket has chosen to deprecate their public API. 

In preparation for this migration, make sure to get an API key from [CoinMarketCap API Signup](https://pro.coinmarketcap.com/signup/) which you will need to access the Current classes in the upcoming version which should be released soon.

**Comment by PyDataBlog** [comment]
> Hi Bernard
> 
> I'm currently using the following code which derives the current value of BTC against US Dollars:
> 
> **# import the Current class from coinsta.core import Current**
> 
> **# get current market information on a specified crypto btc_current = Current.get_current('btc') # a pandas dataframe object**
> 
> **#print(btc_current) btc_current_price = btc_current.loc['price'] [0] print(btc_current_price)**
> 
> However, as I live in the UK, it would be really useful to be able to derive the current value of BTC against GBP (British Pounds), and maybe even EUR (Euros)!
> 
> Best regards,
> Niall

Hi Niall. Coinsta has now been updated to support currency conversions for the current classes. Please upgrade and use your API key to get the data that you want. Over 150 fiat currencies supported currently. Please close the issue if the new implementation works for you.

**Comment by nberrisford** [comment]
Hi Bernard

I have tested the current aspect of the international currency conversion and can confirm that it seems to work well. Great work and many thanks!

Best regards,
Niall

**Comment by PyDataBlog** [comment]
@nberrisford glad that it works!
